### ISSUE TITLE
Add an error message when importing malformed CSV.

### ISSUE THREAD

**Issue by RSLi** [poloclub/argo-graph-lite#31]
While Argo Lite is being used in a class where students import graphs from programmatically generated CSV files, many students created malformed CSV files without the correct quotation strings to escape string values, causing parsing errors during the import process. For example, while Argo Lite is expecting:

```
college, location
"Georgia Tech", "Atlanta, GA"
```

some students might generate

```
college, location
Georgia Tech, Atlanta, GA
```

which is malformed and cannot be imported.

Argo Lite should give a proper error dialog/message (or use the existing NotificationService that generates a toast)  when such error occurs, rather than hanging in the import dialog.

**Comment by oshaikh13** [comment]
I would start by looking here: https://github.com/poloclub/argo-graph-lite/blob/master/argo-lite/src/services/CSVUtils.js
and here: https://github.com/poloclub/argo-graph-lite/blob/master/argo-lite/src/ipc/server.js

My suspicion is that the parser in CSVUtils is throwing some kind of error, but we're not handling it when we use it in server.js!
