### ISSUE TITLE
Argo-graph vs Argo-graph-lite vs Carina

### ISSUE THREAD

**Issue by eljeffeg** [poloclub/argo-graph-lite#43]
Just trying to understand the differences in the Polo Club graph applications.  Can someone explain?

**Comment by FZ2000** [comment]
We started off planning for the visualization tool be a desktop app. And Carina was an early published version of the tool (at WWW). We open-sourced the early prototype as Argo. Argo was a cross-platform electron app (and used SQLite to store graph data). But we found that deploying and maintaining was not straightforward. Importantly, for our users, they still needed to install the app and it was not easy to share their graphs.
This motivated us to “convert” Argo to Argo-lite, a fully in-browser app, no installation needed. Argo-lite saves and loads graph visualizations as graph snapshots, which can be easily shared or embedded as URLs. It doesn’t use electron or SQLite. Argo-lite was published as a CIKM'20 resource paper.
